version: '2'
services:
    # mysql
    db01:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        container_name: db01

    # memcached
    memcached01:
        image: memcached:1.4
        container_name: memcached01

    # redis
    redis01:
        image: redis:3.2
        container_name: redis01

    # web
    web01:
        build: ./web
        ports:
            - "80:80"
            - "443:443"
        links:
            - "api01:api01"
        container_name: web01

    # api
    api01:
        build: ./api
        ports:
            - "23450:23450"
        links:
            - "db01:db01"
        container_name: api01
