version: '2'
services:
    # data
    data:
        image: busybox
        volumes:
            - ./docker-data/mysql:/var/lib/mysql
        container_name: data

    # mysql
    db01:
        build: ./mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes_from:
            - data
        container_name: db01

    # memcached
    memcached01:
        build: ./memcached
        ports:
            - "11211:11211"
        container_name: memcached01

    # redis
    redis01:
        build: ./redis
        ports:
            - "6379:6379"
        container_name: redis01

    # web
    web01:
        build: ./web
        ports:
            - "80:80"
            - "443:443"
        links:
            - "api01:api01"
            - "memcached01:memcached01"
            - "redis01:redis01"
        container_name: web01

    # api
    api01:
        build: ./api
        ports:
            - "8080:80"
        links:
            - "db01:db01"
        container_name: api01
